# problem with GCC 14 in vendored xnnpack
c_compiler_version:     # [aarch64]
  - 13                  # [aarch64]
  - 13                  # [aarch64]
cxx_compiler_version:   # [aarch64]
  - 13                  # [aarch64]
  - 13                  # [aarch64]

MACOSX_SDK_VERSION:         # [osx]
  - 14.5                    # [osx]

channel_targets:
  - conda-forge main
  - conda-forge pytorch_rc
is_rc:
  - False
  - True
zip_keys:
  -
    - channel_targets
    - is_rc

blas_impl:
  - mkl                         # [x86_64]
  # deprioritized on windows, would be nice to have
  - generic                     # [unix]

# https://github.com/conda-forge/.cirun
github_actions_labels:
- blacksmith-16vcpu-ubuntu-2404      # [linux and x86_64]
- blacksmith-16vcpu-ubuntu-2404-arm  # [linux and aarch64]
- blacksmith-12vcpu-macos-latest     # [osx]
- blacksmith-16vcpu-windows-2025     # [win]
