{% set version = "1.8.0" %}
{% set commit = "v1.8.0" %}

package:
  name: pytorch-recipe
  version: {{ version }}

source:
  # for local testing use a tarball including submodules
  git_url: https://github.com/pytorch/pytorch.git
  git_tag: {{ commit }}
  patches:
    # https://github.com/pytorch/pytorch/pull/49281
    - fix_std_stdint.patch
    - fix_dispatch_apply_auto.patch
    # https://github.com/pytorch/pytorch/pull/49646
    - fix_cross_compile.patch
    # https://github.com/pytorch/pytorch/pull/49647
    - fix_blas_lapack.patch

build:
  number: 2

outputs:
  - name: pytorch
    build:
      string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
      string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}                                      # [cuda_compiler_version == "None"]
      detect_binary_files_with_prefix: False
    script: build_pytorch.sh  # [not win]
    script: bld_pytorch.bat   # [win]
    activate_in_script: true
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - numpy                                  # [build_platform != target_platform]
        - cffi                                   # [build_platform != target_platform]
        - sysroot_linux-64  2.17  # [linux64]
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('cuda') }}    # [cuda_compiler_version != "None"]
        # Dec 2020: it seems that git is broken on windows, so we use m2-git
        - patch     # [not win]
        - m2-patch  # [win]
        - git       # [not win]
        - m2-git    # [win]
        - libgomp   # [linux]
        - llvm-openmp    # [osx]
        - cmake
        - git       # [not win]
        - m2-git    # [win]
        - ninja
        - protobuf
        - make      # [linux]
      host:
        # GPU requirements
        - cudnn                           # [cuda_compiler_version != "None"]
        - nccl                            # [cuda_compiler_version != "None"]
        - magma                           # [cuda_compiler_version != "None"]
        # other requirements
        - python
        - numpy
        # dataclasses is a backport of python 3.7 module
        - dataclasses   # [py==36]
        - pip
        - setuptools
        - pyyaml
        - requests
        - future
        - six
        - cffi
        - mkl-devel {{ mkl }}   # [x86]
        - mkl {{ mkl }}         # [x86]
        - libblas * *_mkl       # [x86]
        - libblas               # [not x86]
        - libblas               # [not x86]
        - liblapack             # [not x86]
        - openblas              # [not x86]
        - libprotobuf
        - sleef
        - typing
        - libuv
        - pkg-config  # [unix]
        - typing_extensions
      run:
        - mkl {{ mkl }}     # [x86]
        - libblas * *_mkl   # [x86]
        - libblas   # [not x86]
        - libcblas   # [not x86]
        - liblapack   # [not x86]
        - llvm-openmp    # [osx]
        #- _pytorch_select ==0.1             # [cuda_compiler_version == "None"]
        #- _pytorch_select ==0.2             # [cuda_compiler_version != "None"]
        # GPU requirements without run_exports
        - {{ pin_compatible('cudnn') }}                       # [cuda_compiler_version != "None"]
        - {{ pin_compatible('magma', max_pin='x.x.x') }}      # [cuda_compiler_version != "None"]
        # other requirements
        - python
        - dataclasses   # [py==36]
        - {{ pin_compatible('numpy') }}
        - cffi
        # if future isn't installed on python 3, `pip check` can give
        # the user an error
        - future
        - typing  # [py2k]
        - typing_extensions
        # Need ninja to load C++ extensions
        - ninja

    test:
      requires:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - setuptools
        - hypothesis
        - pytest
        - tabulate
        - pydot
        - mock  # [linux]
        - pip
      imports:
        - torch
      source_files:
        - test
      commands:
        - OMP_NUM_THREADS=4 python ./test/run_test.py || true  # [not win]
        - python ./test/run_test.py  # [win]
        # Run pip check so as to ensure that all pytorch packages are installed
        # https://github.com/conda-forge/pytorch-cpu-feedstock/issues/24
        - pip check

  - name: pytorch-cpu   # [cuda_compiler_version == "None"]
  - name: pytorch-gpu   # [cuda_compiler_version != "None"]
    build:
      string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
      string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}                                      # [cuda_compiler_version == "None"]
      detect_binary_files_with_prefix: False
      # weigh down cpu implementation and give cuda preference
      track_features:
        - pytorch-cpu                                      # [cuda_compiler_version == "None"]
    requirements:
      run:
        - {{ pin_subpackage("pytorch", exact=True) }}
    test:
      commands:
        - echo "hello world"

about:
  home: https://pytorch.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: PyTorch is an optimized tensor library for deep learning using GPUs and CPUs.

extra:
  recipe-maintainers:
    - hmaarrfk
    - sodre
  feedstock-name: pytorch-cpu
