{% set version = "1.6.0" %}

package:
  name: pytorch-cpu
  version: {{ version }}

source:
  # The tar source needs serious patching since it is trying to build
  # all 3rd party modules
  # url: https://github.com/pytorch/pytorch/archive/v{{ version }}.tar.gz
  # fn: pytorch-v{{ version }}.tar.gz
  # sha256: f360b7954e441bc5c4b36c49e711697a5c351de8b146c2982809385e3b3cfdcb
  git_url: https://github.com/pytorch/pytorch.git
  git_tag: v{{ version }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - make  # [unix]
  host:
    - python
    - pip
    - pyyaml
    - numpy
    - setuptools
    - cffi
    - ninja
    # 3rd party libraries that we are unbundling
    - pybind11
    # They seem to be pinned to something like protobuf 3.5
    # maybe we can remove this pin?
    # - protobuf  #  3.5
  run:
    - python
    - {{ pin_compatible('numpy') }}
    # ninja and cffi are included in
    - ninja
    - cffi
    - typing_extensions

test:
  imports:
    - torch
    # Maybe we should have a test for a simple Neural Network???

about:
  home: https://pytorch.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "PyTorch is an optimized tensor library for deep learning using GPUs and CPUs."

extra:
  recipe-maintainers:
    - hmaarrfk
    - sodre
