azure:
  settings_osx:
    pool:
      vmImage: macos-12
  store_build_artifacts: true
build_platform:
  osx_arm64: osx_64
  linux_aarch64: linux_64
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
os_version:
  linux_64: cos7
provider:
  linux_aarch64: azure
  linux_64: ["github_actions"]
  osx_64: ["github_actions"]
  win_64: ["github_actions"]
test_on_native_only: true
conda_build:
  pkg_format: '2'
# https://github.com/conda-forge/conda-smithy/pull/1686
remote_ci_setup:
- py-lief=0.12.3
- conda-forge-ci-setup=3
