azure:
  free_disk_space: true
  settings_linux:
    timeoutInMinutes: 1
bot:
  abi_migration_branches:
  - v2.9.x
build_platform:
  linux_aarch64: linux_64
  osx_64: osx_arm64
conda_build:
  pkg_format: '2'
  # use highest possible compression (smaller package -> less upload time) to try to
  # combat timouts on windows see https://github.com/conda/infrastructure/issues/1159
  zstd_compression_level: 22
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
github_actions:
  resize_win_partitions: true
  self_hosted: true
  store_build_artifacts: true
  timeout_minutes: 1440
  triggers:
  - push
  - pull_request
provider:
  linux_64: github_actions
  osx_arm64: github_actions
  win_64: github_actions
test: native_and_emulated
