azure:
  free_disk_space: true
  settings_linux:
    timeoutInMinutes: 1
  settings_win:
    variables:
      CONDA_BLD_PATH: C:\\bld\\
build_platform:
  linux_aarch64: linux_64
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
github_actions:
  self_hosted: true
  timeout_minutes: 900
  triggers:
  - push
  - pull_request
provider:
  linux_64: github_actions
  linux_aarch64: azure
  win_64: github_actions
test: native_and_emulated

