azure:
  free_disk_space: true
  settings_linux:
    timeoutInMinutes: 1
build_platform:
  linux_aarch64: linux_64
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
github_actions:
  self_hosted: true
  timeout_minutes: 720
  triggers:
  - push
  - pull_request
os_version:
  linux_64: cos7
provider:
  linux_64: azure
  linux_aarch64: azure
test: native_and_emulated
