azure:
  settings_win:
    pool:
      vmImage: windows-2019
  store_build_artifacts: true
build_platform:
  osx_arm64: osx_64
conda_forge_output_validation: true
os_version:
  linux_64: cos7
test_on_native_only: true
github:
  branch_name: main
  tooling_branch_name: main
