azure:
  store_build_artifacts: true
build_platform:
  osx_arm64: osx_64
conda_forge_output_validation: true
os_version:
  linux_64: cos7
github_actions:
  self_hosted: true
provider:
  linux_64:
  - azure
  - github_actions
conda_build:
  pkg_format: '2'
test: native_and_emulated
