azure:
  free_disk_space: true
  settings_linux:
    timeoutInMinutes: 1
bot:
  abi_migration_branches:
  - v2.5.x
build_platform:
  linux_aarch64: linux_64
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
github_actions:
  self_hosted: true
  store_build_artifacts: true
  timeout_minutes: 900
  triggers:
  - push
  - pull_request
provider:
  linux_64: github_actions
  linux_aarch64: azure
  win_64: github_actions
test: native_and_emulated
