appveyor:
  # We need visual studio 2017 to build pytorch (kept for reference)
  # not that it matters since we build on Azure anyway
  image: Visual Studio 2017
provider:
  osx: circle
  # Appveyor can't complete the job for windows
  win: azure

azure:
  # Windows packages are only built on Azure
  upload_packages: true
  # Force is OK, but I don't want to upload packages from multiple CIs at once
  # That said, the linux builds seem to fail
  force: false
conda_forge_output_validation: true
