azure:
  settings_osx:          # [osx_impl == "mps"]
    pool:                # [osx_impl == "mps"]
      vmImage: macos-12  # [osx_impl == "mps"]
  settings_win:
    pool:
      vmImage: windows-2019
  store_build_artifacts: true
build_platform:
  osx_arm64: osx_64
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
os_version:
  linux_64: cos7
remote_ci_setup:
- conda-forge-ci-setup=3
- conda-forge/label/lief_dev::py-lief
- conda-forge/label/lief_dev::liblief
test_on_native_only: true
