azure:
  free_disk_space: true
  settings_osx:
    pool:
      vmImage: macos-12
  store_build_artifacts: true
build_platform:
  linux_aarch64: linux_64
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
os_version:
  linux_64: cos7
provider:
  linux_aarch64: azure
remote_ci_setup:
- py-lief=0.12.3
- conda-forge-ci-setup=3
test_on_native_only: true
