# Windows builds of pytorch with python 2.7 are very experimental.
# Finally, pytorch requires MSVC2017
# As of making this recipe, it only exists on defaults.
# Leave conda_build_config.yaml alone unless it is windows
c_compiler:                    # [win]
  - vs2017                     # [win]
  - vs2017                     # [win]
cxx_compiler:                  # [win]
  - vs2017                     # [win]
  - vs2017                     # [win]
vc:                            # [win]
  - 14.1                       # [win]
  - 14.1                       # [win]
python:                        # [win]
  - 3.6                        # [win]
  - 3.7                        # [win]
